export const actions = {
  ADD_POST: "ADD-POST",
  DELETE_POST: "DELETE-POST",
  TOGGLE_LIKE_POST: "TOGGLE-LIKE-POST",
  SET_USER_PROFILE: "SET-USER-PROFILE",

  SEND_MESSAGE: "SEND-MESSAGE",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE-NEW-MESSAGE-BODY",

  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  SET_USERS: "SET-USERS",

  SET_CURRENT_PAGE: "SET-CURRENT-PAGE",
  SET_TOTAL_USERS_COUNT: "SET-TOTAL-USERS-COUNT",

  TOGGLE_IS_FETCHING: "TOGGLE-IS-FETCHING",
  TOGGLE_IS_FOLLOWING_PROGRESS: "TOGGLE-IS-FOLLOWING-PROGRESS",

  // SET_USER_DATA: "samurai-network/auth/SET-USER-DATA",
  // GET_CAPTCHA_URL_SUCCESS: "samurai-network/auth/GET-CAPTCHA-URL-SUCCESS",
  SET_USER_DATA: "samurai-network/auth/SET-USER-DATA",
  GET_CAPTCHA_URL_SUCCESS: "samurai-network/auth/GET-CAPTCHA-URL-SUCCESS",
  SET_STATUS: "SET-STATUS",

  INITIALIZED_SUCCESS: "INITIALIZED-SUCCESS",

  SAVE_PHOTO_SUCCESS: "SAVE-PHOTO-SUCCESS",
};
