export const actions = {
  ADD_POST: "ADD-POST",
  UPDATE_NEW_POST_TEXT: "UPDATE-NEW-POST-TEXT",
  TOGGLE_LIKE_POST: "TOGGLE-LIKE-POST",
  SET_USER_PROFILE: "SET-USER-PROFILE",

  SEND_MESSAGE: "SEND-MESSAGE",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE-NEW-MESSAGE-BODY",

  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  SET_USERS: "SET-USERS",

  SET_CURRENT_PAGE: "SET-CURRENT-PAGE",
  SET_TOTAL_USERS_COUNT: "SET-TOTAL-USERS-COUNT",

  TOGGLE_IS_FETCHING: "TOGGLE-IS-FETCHING",

  SET_USER_DATA: "SET-USER-DATA",
};
