export const actions = {
  ADD_POST: "ADD-POST",
  UPDATE_NEW_POST_TEXT: "UPDATE-NEW-POST-TEXT",
  TOGGLE_LIKE_POST: "TOGGLE-LIKE-POST",

  SEND_MESSAGE: "SEND-MESSAGE",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE-NEW-MESSAGE-BODY",
};
